#!/usr/bin/env node
const fs = require('fs')
const path = require('path')
const { mdToPdf } = require('md-to-pdf')
const { exec } = require('child_process')

/*    understand/
 * main entry point into our program
 *
 *    way/
 * find all user documentation comments and check them against
 * the README.md. Display any not found or, if all found, open
 * the README as pdf.
 */
function main() {
  const readme = readreadme()
  const docs = xtractUserDocz()
  if(!docs) return console.log("no documentation comments //** found")
  const missing = checkAgainstReadme(readme, docs)
  if(!missing) openPDF(readme)
  else display(readme, missing)
}

/*    way/
 * read the README.md file in the current directory
 */
function readreadme() {
  try {
    return fs.readFileSync('README.md', 'utf8')
  } catch(e) {
    if(e.code === 'ENOENT') return ""
    throw e
  }
}

/*    way/
 * extract user documentation comment lines from
 * all javascript files, ignoring .gitignore files
 */
function xtractUserDocz() {
  const docs = {}

  x_1('.')
  if(Object.keys(docs).length) return docs

  function x_1(p) {
    const ntries = fs.readdirSync(p, { withFileTypes: true })
    ntries.map(ntry => {
      if(ntry.isDirectory() && is_ok_1(ntry.name)) return x_1(path.join(p, ntry.name))
      if(!ntry.isFile()) return
      if(ntry.name && ntry.name.endsWith(".js")) xtract_1(path.join(p, ntry.name))
    })
  }

  function is_ok_1(n) {
    if(!n) return
    if(n === 'node_modules') return
    if(n.startsWith('.')) return
    if(n === 'dist') return
    if(n === 'tmp' || n === '_tmp') return

    return true
  }

  function xtract_1(f) {
    const data = fs.readFileSync(f, "utf8")
    const lines = data.split(/[\r\n]+/g)
    lines.map(l => {
      const m = l.match(/\/\/\*\* ?(.*)/)
      if(!m) return
      if(!docs[f]) docs[f] = []
      docs[f].push(m[1])
    })
  }
}

/*    way/
 * walk each documentation line and check that
 * it is present in the readme, returning missing lines
 */
function checkAgainstReadme(readme, docs) {
  const lines = readme.split(/\r\n|\n|\r/g)
  const missing = {}
  for(let f in docs) {
    const issing = docs[f].filter(l => {
      const ndx = lines.indexOf(l)
      if(ndx === -1) return true
      lines.splice(ndx, 1)
    })
    if(issing && issing.length) missing[f] = issing
  }
  if(Object.keys(missing).length) return missing
}

/*    way/
 * generate and open pdf
 */
async function openPDF(readme) {
  const dest = "./README.pdf"
  await mdToPdf({ path: 'README.md' }, { dest }).catch(console.error)
  openItem(dest)
}

/*    way/
 * call the default open application based on platform
 */
function openItem(n) {
  switch (process.platform) {
    case 'darwin' : return exec('open ' + n)
    case 'win32' : return exec('start ' + n)
    case 'win64' : return exec('start ' + n)
    default : return exec('xdg-open ' + n)
  }
}

/*    way/
 * show the missing lines
 */
function display(readme, missing) {
  console.log("README missing these lines:")
  for(let f in missing) {
    console.log("\n" + f +":")
    missing[f].map(l => console.log(l))
  }
}

main()
