#!/usr/bin/env node
const fs = require('fs')

/*    understand/
 * main entry point into our program
 *
 *    way/
 * find all user documentation comments and check them against
 * the README.md. Display any not found or, if all found, open
 * the README as pdf.
 */
function main() {
  const readme = readreadme()
  const docs = xtractUserDocz()
  const missing = checkAgainstReadme(readme, docs)
  if(!missing) openPDF(readme)
  else display(readme, missing)
}

/*    way/
 * read the README.md file in the current directory
 */
function readreadme() {
  try {
    return fs.readFileSync('README.md', 'utf8')
  } catch(e) {
    if(e.code === 'ENOENT') return ""
    throw e
  }
}

function xtractUserDocz() {
}

function checkAgainstReadme() {
}

function openPDF() {
}

function display() {
}

main()
