#!/usr/bin/env node
const fs = require('fs')
const path = require('path')

/*    understand/
 * main entry point into our program
 *
 *    way/
 * find all user documentation comments and check them against
 * the README.md. Display any not found or, if all found, open
 * the README as pdf.
 */
function main() {
  const readme = readreadme()
  const docs = xtractUserDocz()
  const missing = checkAgainstReadme(readme, docs)
  if(!missing) openPDF(readme)
  else display(readme, missing)
}

/*    way/
 * read the README.md file in the current directory
 */
function readreadme() {
  try {
    return fs.readFileSync('README.md', 'utf8')
  } catch(e) {
    if(e.code === 'ENOENT') return ""
    throw e
  }
}

/*    way/
 * extract user documentation comment lines from
 * all javascript files, ignoring .gitignore files
 */
function xtractUserDocz() {
  const docs = {}

  x_1('.')
  return docs

  function x_1(p) {
    const ntries = fs.readdirSync(p, { withFileTypes: true })
    ntries.map(ntry => {
      if(ntry.isDirectory() && is_ok_1(ntry.name)) return x_1(path.join(p, ntry.name))
      if(!ntry.isFile()) return
      if(ntry.name && ntry.name.endsWith(".js")) xtract_1(path.join(p, ntry.name))
    })
  }

  function is_ok_1(n) {
    if(!n) return
    if(n === 'node_modules') return
    if(n.startsWith('.')) return
    if(n === 'dist') return
    if(n === 'tmp' || n === '_tmp') return

    return true
  }

  function xtract_1(f) {
    const data = fs.readFileSync(f, "utf8")
    const lines = data.split(/[\r\n]+/g)
    lines.map(l => {
      const m = l.match(/\/\/\*\* ?(.*)/)
      if(!m) return
      if(!docs[f]) docs[f] = []
      docs[f].push(m[1])
    })
  }
}

/*    way/
 * walk each documentation line and check that
 * it is present in the readme, returning missing lines
 */
function checkAgainstReadme(readme, docs) {
  const lines = readme.split(/[\r\n]+/g).filter(l => l.trim())
  const missing = {}
  for(let f in docs) {
    const issing = docs[f].filter(l => l.trim()).filter(l => lines.indexOf(l) === -1)
    if(issing && issing.length) missing[f] = issing
  }
  if(Object.keys(missing).length) return missing
}

function openPDF(readme) {
  console.log('opening pdf')
}

/*    way/
 * show the missing lines
 */
function display(readme, missing) {
  console.log("README missing these lines:")
  for(let f in missing) {
    console.log("\n" + f +":")
    missing[f].map(l => console.log(l))
  }
}

main()
